Add updateLine variant of addOrUpdateLine
This will only update an existing PATTERN with a REPLACEMENT, but won't add anything should no match exist. Therefore, no --line LINE needs to be given, but both --update-match PATTERN and --replacement REPLACEMENT are mandatory. Because of that, --create-nonexisting does not make sense here, neither do --pre-line and --post-line.
The adaptations of addOrUpdateLine are surprisingly small; mostly it's the changed command-line argument parsing. The command is reused through a new wrapper script; integrating the functionality directly into addOrUpdateLine would have made the usage help really messy; in the wrapper we're going to massage that instead.
The functionality is enabled via the ADDORUPDATELINE_NO_APPEND environment variable; it makes the LINE never match (so triggering only happens through PATTERN), and turns off the isAppend flag for all passed files (instead of just for files other than the last).

diff --git a/bin/addOrUpdateLine b/bin/addOrUpdateLine
--- a/bin/addOrUpdateLine
+++ b/bin/addOrUpdateLine
@@ -143,8 +143,18 @@ do
 	*)		    break;;
     esac
 done
-if [ -z "$line" ]; then
+if [ ! "$ADDORUPDATELINE_NO_APPEND" ] && [ -z "$line" ]; then
     echo 'ERROR: No LINE passed.'
+    echo
+    printUsage "$0"
+    exit 2
+elif [ "$ADDORUPDATELINE_NO_APPEND" ] && [ -z "$updateMatch" ]; then
+    echo 'ERROR: No --update-match PATTERN passed.'
+    echo
+    printUsage "$0"
+    exit 2
+elif [ "$ADDORUPDATELINE_NO_APPEND" ] && [ -z "${replacement+t}" ]; then
+    echo 'ERROR: No --replacement REPLACEMENT passed.'
     echo
     printUsage "$0"
     exit 2
@@ -153,7 +163,7 @@ elif [ ${#sedInplaceArgs[@]} -gt 0 -a -n "$isTestOnly" ]; then
     echo
     printUsage "$0"
     exit 2
-elif [ -n "$isIgnoreNonexisting" -a -n "$isCreateNonexisting" ]; then
+elif [ "$isIgnoreNonexisting" ] && [ "$isCreateNonexisting" ]; then
     echo 'ERROR: Cannot combine --ignore-nonexisting and --create-nonexisting.'
     echo
     printUsage "$0"
@@ -163,11 +173,20 @@ elif [ -n "$addBeforeAddress" -a -n "$addAfterAddress" ]; then
     echo
     printUsage "$0"
     exit 2
+elif [ "$ADDORUPDATELINE_NO_APPEND" ] && [ "$isCreateNonexisting" ]; then
+    echo 'ERROR: Cannot use --create-nonexisting when appending is not allowed.'
+    echo
+    printUsage "$0"
+    exit 2
 fi >&2
 
 insertableLine="${line//\\/\\\\}"
 insertableLine="${insertableLine//${NL}/\\${NL}}"
-literalLinePattern="^$(printf %s "$line" | literalPattern)\$"
+if [ "$ADDORUPDATELINE_NO_APPEND" ]; then
+    literalLinePattern='\n'  # Never matches in a line.
+else
+    literalLinePattern="^$(printf %s "$line" | literalPattern)\$"
+fi
 [ "$updateMatch" ] || updateMatch="$literalLinePattern"
 
 [ $# -eq 0 ] && set -- -    # Read from stdin if no FILE is passed.
@@ -193,7 +212,7 @@ create()
 }
 process()
 {
-    local isAppend="$1"; shift
+    local isAppend="$1"; shift; [ "$ADDORUPDATELINE_NO_APPEND" ] && isAppend=
     local filespec="$1"; shift
 
     typeset -a sedProgram=()
